version: "3.9"

volumes:
  postgis-data:
    driver: local
  postgis-data-test:
    driver: local

services:
  db:
    image: jkr/postgis
    build:
      context: ./docker/postgis
    volumes:
      - postgis-data:/var/lib/postgresql/data
      - ./docker/postgis/init_db:/docker-entrypoint-initdb.d
      - ./docker/postgis/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./docker/postgis/logs:/var/log/postgresql
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - JKR_DB=${JKR_DB}
      - JKR_USER=${JKR_USER}
      - JKR_PASSWORD=${JKR_PASSWORD}
    ports:
      - ${JKR_DB_PORT}:5432
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

  db_test:
    image: jkr/postgis
    build:
      context: ./docker/postgis/test
    volumes:
      - postgis-data-test:/var/lib/postgresql/data
      - ./docker/postgis/test/init_test_db:/docker-entrypoint-initdb.d
      - ./docker/postgis/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./docker/postgis/test/logs:/var/log/postgresql
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - JKR_TEST_DB=${JKR_TEST_DB}
      - JKR_USER=${JKR_USER}
      - JKR_PASSWORD=${JKR_PASSWORD}
      - PGPORT=5433
    ports:
      - ${JKR_TEST_DB_PORT}:5433
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

  flyway:
    image: flyway/flyway
    depends_on:
      - db
    profiles: [ "migration" ]
    environment:
      - FLYWAY_USER=${JKR_USER}
      - FLYWAY_PASSWORD=${JKR_PASSWORD}
      - FLYWAY_URL=jdbc:postgresql://db/${JKR_DB}
    volumes:
      - ./db/migrations:/flyway/sql
      - ./db/flyway.conf:/flyway/conf/flyway.conf
    command: migrate

  flyway_test:
    image: flyway/flyway
    depends_on:
      - db_test
    profiles: [ "migration" ]
    environment:
      - FLYWAY_USER=${JKR_USER}
      - FLYWAY_PASSWORD=${JKR_PASSWORD}
      - FLYWAY_URL=jdbc:postgresql://db_test:5433/${JKR_TEST_DB}
    volumes:
      - ./db/migrations:/flyway/sql
      - ./db/flyway.conf:/flyway/conf/flyway.conf
    command: migrate

  tbls:
    image: k1low/tbls:latest
    depends_on:
      - db
    profiles: [ "dev" ]
    volumes:
      - ./docs/db:/work/db
      - ./db/.tbls.yml:/work/.tbls.yml
    command: doc --rm-dist -c /work/.tbls.yml postgres://${JKR_USER}:${JKR_PASSWORD}@db:5432/${JKR_DB}?sslmode=disable /work/db
